# Generated by Django 6.0.5 on 2026-06-12 18:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('section', models.CharField(max_length=50)),
                ('bloc', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('occupe', 'Occupé'), ('non_exploitable', 'Non exploitable')], default='disponible', max_length=20)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField()),
                ('caveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.caveau')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.caveau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('defunt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.defunt')),
            ],
        ),
    ]
